# netlify site URL: https://csharp-web-dev-curriculum.netlify.app

[build]
  command = "hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.130.0"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"
  HUGO_VERSION = "0.130.0"
